### ISSUE TITLE
Mac release build failed on mac 10.13

### ISSUE THREAD

**Issue by ailisp** [nearprotocol/nearcore#2784]
Today i tried run the mac binary build on mac 10.13, unfortunately get errors like 
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/bo/.nearup/near/betanet/near (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/bo/.nearup/near/betanet/near (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

Doing a quick search online, it seems old mac binary build work on newer mac, but opposite doesn't. And, unfortunately github actions only have mac 10.15 runner. @chefsale Do you know some good alternative to build portable mac binary on a 10.15 mac or another mac cloud provider that provide old macs. Thanks

**Comment by ailisp** [comment]
Also, we have about 5% of fail because github action runner is too weak, it's desirable to find a 10.13, paid mac cloud hosting

**Comment by ailisp** [comment]
Why this is closed? without build near binary in an earlier Mac, people with mac 10.13 or 10.14 will not able to run official build binary

**Comment by chefsale** [comment]
Because we haven't build a mac binary in months.
